### ISSUE TITLE
Transferring to IrisSat

### ISSUE THREAD

**Issue by aminya** [IrisSat/IrisSat-Flight-Software#11]
As you may know, after the naming competition in the province, the name of the satellite has changed to "Iris". I have created an organization with this new name. 
https://github.com/IrisSat

We should transfer this repository to that organization. I have invited you, so you should be able to do that.

We should also rename the repository to Iris-Flight-Software

**Comment by joehowarth17** [comment]
@aminya The repository is transferred. You should be able to rename it now since you are the owner.

**Comment by aminya** [comment]
Thanks, Joseph!
