### ISSUE TITLE
Change Project to Use C++ Compiler

### ISSUE THREAD

**Issue by joehowarth17** [IrisSat/IrisSat-Flight-Software#17]
So here is some initial research:

For using C++ and C together:
https://isocpp.org/wiki/faq/mixing-c-and-cpp 

It seems that this is easy enough provided the c code (or c++ code) is wrapped in "extern c".
And we will have to setup the project to use both compilers, since we don't want to modify all the c code (libraries and vendor drivers etc.).

---

Here is a link about using FreeRTOS with C+:
https://www.freertos.org/FreeRTOS_Support_Forum_Archive/February_2017/freertos_FreeRTOSs_compatibility_with_C_2aa2a047j.html

So it seems possible, given a few restrictions. Not sure if we can use the STL. But there might be an alternative standard library, Embedded Template Library (ETL).

---

The drivers generated by Microsemi seem to have extern C, so at a first look these should just work.
Same with CSP and littleFS.

---

So the next steps would be to figure out how to get softconsole to compile using both compilers, and then just try compiling the current project, with minimal changes.

At this point it doesn't seem too difficult, but if we run into lots of problems then it might not be worth it switching to C++, since we would still need to re-write portions of the code to take advantage. Also certain C++ features can use lots of memory so we would have to be careful not to use these.

**Comment by aminya** [comment]
The project can use C++ by doing this:
![image](https://user-images.githubusercontent.com/16418197/102727303-8967e500-42ea-11eb-9bbe-49db8a5a0151.png)
![image](https://user-images.githubusercontent.com/16418197/102727319-a1d7ff80-42ea-11eb-8dd8-5f29ae7b6783.png)

However, there is a linker error once we do this. `_eheap` is defined by a linker script, which does not seem to be defined after the conversion:

```shell
c:/microchip/softconsole-v6.5/arm-none-eabi-gcc/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld.exe: ./firmware/CMSIS/startup_gcc/newlib_stubs.o: in function `_sbrk':
C:\Users\aminy\Documents\GitHub\Cpp\IrisSat-Flight-Software\iris-fsw-softconsole\Debug/../firmware/CMSIS/startup_gcc/newlib_stubs.c:267: undefined reference to `_eheap'
collect2.exe: error: ld returned 1 exit status
make: *** [makefile:94: iris-fsw-softconsole.elf] Error 1
```
